name: Publish to GH Pages

on:
  push:
    branches:
      - main
      - route


env:
  NODE_VERSION: '14.x' # set this to the node version to use

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install
        run: npm install
      - name: npm test
        run: npm run test --if-present
      - name: npm build
        env:
          VUE_APP_BIN_KEY: ${{ secrets.VUE_APP_BIN_KEY }}
          VUE_APP_COLLECTION_ID: ${{ secrets.VUE_APP_COLLECTION_ID }}
        run: NODE_ENV=production npm run build --if-present
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist
          fqdn: matheus.sampaio.us/ao-loot-logger-viewer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
